[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
[rpc_endpoints]
mantle_sepolia = "https://rpc.sepolia.mantle.xyz"

[etherscan]
mantle_sepolia = { key = "${MANTLE_EXPLORER_KEY}", url = "https://explorer.sepolia.mantle.xyz/api" }
